// Unminified from: _next/unpacked/modules/layout/791646/0130__tu.js (FONTS_DEFAULT, `tu`)
//                   _next/unpacked/modules/layout/791646/0131__th.js (FONTS_PRO,     `th`)
//
// Both arrays are copied verbatim. `tu` are the open-source fonts served by
// the editor directly (via /fonts/*.woff2); `th` is the Adobe-hosted set
// gated by Pro subscriptions (loaded with the Adobe Web Fonts typekit).

export interface FontDef {
  name: string;
  type?: string;
  fontFamily?: string;
  weights?: number[];
  offset: number;
  variable?: boolean;
  italics?: boolean;
  regular?: number;
  source?: string;
}

/** Original name: `tu`. */
export const FONTS_DEFAULT: FontDef[] = 
[
          {
            name: "Albert Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Alegreya",
            type: "serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: 2,
            variable: true,
            italics: true,
          },
          {
            name: "Amulya",
            type: "sans-serif",
            weights: [300, 425, 500, 600, 700],
            regular: 425,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Archivo Narrow",
            type: "sans-serif",
            weights: [400, 500, 600, 700],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Archivo",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Besley",
            type: "serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Bespoke Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Bespoke Serif",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Bespoke Slab",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Bevellier",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Bitter",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Boska",
            type: "serif",
            weights: [400, 500, 600, 700, 800, 900],
            regular: 500,
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Bricolage Grotesque",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            regular: 375,
            offset: 0,
            variable: true,
            italics: false,
          },
          { name: "Chubbo", type: "serif", weights: [300, 400, 500, 600, 700], offset: 1, variable: true, italics: true },
          {
            name: "Clash Display",
            type: "sans-serif",
            weights: [300, 425, 500, 600, 700],
            regular: 425,
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Clash Grotesk",
            type: "sans-serif",
            weights: [300, 425, 500, 600, 700],
            regular: 425,
            offset: 1,
            variable: true,
            italics: false,
          },
          {
            name: "Crimson Pro",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 3,
            variable: true,
            italics: true,
          },
          { name: "Departure Mono", type: "monospace", weights: [400], offset: -1, variable: false, italics: false },
          {
            name: "DM Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "EB Garamond",
            type: "serif",
            weights: [400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Figtree",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Fira Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Fraunces",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            regular: 350,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Gambetta",
            type: "serif",
            weights: [300, 450, 600, 700],
            regular: 450,
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Geist Mono",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: false,
          },
          { name: "Geist", type: "sans-serif", weights: [400, 500, 600, 700], offset: 0, variable: true, italics: false },
          {
            name: "General Sans",
            type: "sans-serif",
            weights: [300, 450, 500, 600, 700],
            regular: 450,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Grandstander",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "iA Writer Mono",
            type: "monospace",
            weights: [400, 500, 600, 700],
            regular: 425,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "iA Writer Quattro",
            type: "sans-serif",
            weights: [400, 500, 600, 700],
            regular: 425,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "IBM Plex Mono",
            type: "monospace",
            weights: [300, 400, 500, 600, 700],
            offset: 0,
            variable: false,
            italics: true,
          },
          {
            name: "IBM Plex Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "IBM Plex Serif",
            type: "serif",
            weights: [300, 400, 500, 600, 700],
            offset: 0,
            variable: false,
            italics: true,
          },
          {
            name: "Inconsolata",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800, 900],
            regular: 450,
            offset: 3,
            variable: true,
            italics: false,
          },
          {
            name: "Instrument Sans",
            type: "sans-serif",
            weights: [400, 500, 600, 700],
            offset: 0,
            variable: true,
            italics: true,
          },
          { name: "Instrument Serif", type: "serif", weights: [400], offset: 3, variable: false, space: 0, italics: true },
          {
            name: "Inter",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Iosevka",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 1,
            variable: false,
            italics: true,
          },
          {
            name: "Jet Brains Mono",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Karla",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Lato",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 900],
            offset: 0,
            variable: false,
            italics: true,
          },
          {
            name: "Lexend",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            regular: 350,
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Libre Caslon Condensed",
            type: "serif",
            weights: [400, 500, 600, 700],
            regular: 400,
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Libre Franklin",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          { name: "Lora", type: "serif", weights: [400, 500, 600, 700], offset: 0, variable: true, italics: true },
          {
            name: "Manrope",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            regular: 450,
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Merriweather Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Merriweather",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Mona Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Montserrat",
            type: "sans-serif",
            weights: [300, 450, 600, 700, 800, 900],
            regular: 450,
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Nunito Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Nunito",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Open Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Oswald",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            regular: 350,
            offset: 1,
            variable: true,
            italics: false,
          },
          {
            name: "Outfit",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Pilcrow Rounded",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: 1,
            variable: true,
            italics: false,
          },
          {
            name: "Playfair Display",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Playpen Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Plein",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Plus Jakarta Sans",
            type: "sans-serif",
            weights: [300, 450, 600, 700, 800],
            regular: 450,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Poppins",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Public Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Quicksand",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            regular: 500,
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Raleway",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            regular: 500,
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Ranade",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            offset: -1,
            variable: true,
            italics: true,
          },
          { name: "Recia", type: "serif", weights: [300, 400, 500, 600, 700], offset: 0, variable: true, italics: true },
          {
            name: "Roboto Mono",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Roboto Serif",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Roboto Slab",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Roboto",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Rubik",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Satoshi",
            type: "sans-serif",
            weights: [300, 400, 500, 700, 900],
            regular: 450,
            offset: 0,
            variable: true,
            italics: true,
          },
          { name: "Sentient", type: "serif", weights: [300, 400, 500, 600, 700], offset: 0, variable: true, italics: true },
          {
            name: "Shantell Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Sora",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: -1,
            variable: true,
            italics: true,
          },
          {
            name: "Source Code Pro",
            type: "monospace",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          {
            name: "Source Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Source Serif",
            type: "serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Space Grotesk",
            type: "sans-serif",
            weights: [300, 450, 600, 700],
            regular: 450,
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Spline Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700],
            offset: 0,
            variable: true,
            italics: false,
          },
          {
            name: "Supreme",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800],
            offset: 1,
            variable: true,
            italics: true,
          },
          {
            name: "Switzer",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
          { name: "Syne", type: "sans-serif", weights: [400, 500, 600, 700], offset: 1, variable: true, italics: false },
          {
            name: "Work Sans",
            type: "sans-serif",
            weights: [300, 400, 500, 600, 700, 800, 900],
            offset: 0,
            variable: true,
            italics: true,
          },
        ];

/** Original name: `th`. */
export const FONTS_PRO: FontDef[] = 
[
          {
            name: "Adelle\xa0Sans",
            fontFamily: "adelle-sans",
            type: "sans-serif",
            weights: [400, 600, 700, 800, 900],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Adelle",
            fontFamily: "adelle",
            type: "serif",
            weights: [400, 600, 700, 800, 900],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Adobe Garamond",
            fontFamily: "adobe-garamond-pro",
            type: "serif",
            weights: [400, 600, 700],
            offset: 2,
            source: "adobe",
          },
          {
            name: "Arpona",
            fontFamily: "arpona",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Brandon Grotesque",
            fontFamily: "brandon-grotesque",
            type: "sans-serif",
            weights: [400, 500, 700, 900],
            offset: 3,
            source: "adobe",
          },
          {
            name: "Calluna Sans",
            fontFamily: "calluna-sans",
            type: "sans-serif",
            weights: [400, 600, 700, 900],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Calluna",
            fontFamily: "calluna",
            type: "serif",
            weights: [400, 600, 700],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Colfax",
            fontFamily: "colfax-web",
            type: "sans-serif",
            weights: [400, 500, 700, 900],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Crimson Text",
            fontFamily: "Crimson Text",
            type: "serif",
            weights: [400, 600, 700],
            offset: 2,
            source: "google",
          },
          {
            name: "Degular",
            fontFamily: "degular",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800],
            offset: 2,
            source: "adobe",
          },
          {
            name: "DM Sans",
            fontFamily: "DM Sans",
            type: "sans-serif",
            weights: [400, 500, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "Figtree",
            fontFamily: "Figtree",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800],
            offset: 0,
            source: "local",
          },
          {
            name: "Freight Sans",
            fontFamily: "freight-sans-pro",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 900],
            offset: 2,
            source: "adobe",
          },
          {
            name: "Freight Text",
            fontFamily: "freight-text-pro",
            type: "serif",
            weights: [400, 500, 600, 700, 900],
            offset: 2,
            source: "adobe",
          },
          {
            name: "Granville",
            fontFamily: "granville",
            type: "sans-serif",
            weights: [400, 700],
            offset: 2,
            source: "adobe",
          },
          {
            name: "Halyard Text",
            fontFamily: "halyard-text",
            type: "sans-serif",
            weights: [300, 500, 600, 700, 900],
            offset: 0,
            source: "adobe",
          },
          {
            name: "IBM Plex Mono",
            fontFamily: "IBM Plex Mono",
            type: "monospace",
            weights: [400, 500, 600, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "IBM Plex Sans",
            fontFamily: "IBM Plex Sans",
            type: "sans-serif",
            weights: [400, 500, 600, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "IBM Plex Serif",
            fontFamily: "IBM Plex Serif",
            type: "serif",
            weights: [400, 500, 600, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "Inter",
            fontFamily: "Inter",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800],
            offset: 0,
            source: "local",
          },
          {
            name: "IvyPresto Text",
            fontFamily: "ivypresto-text",
            type: "serif",
            weights: [400, 600, 700],
            offset: 0,
            source: "adobe",
          },
          {
            name: "New Spirit",
            fontFamily: "new-spirit",
            type: "serif",
            weights: [400, 500, 600, 700],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Nunito Sans",
            fontFamily: "Nunito Sans",
            type: "sans-serif",
            weights: [400, 600, 700, 800, 900],
            offset: 0,
            source: "google",
          },
          {
            name: "Orpheus Pro",
            fontFamily: "orpheuspro",
            type: "serif",
            weights: [400, 500, 700],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Playfair Display",
            fontFamily: "Playfair Display",
            type: "serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: 0,
            source: "google",
          },
          {
            name: "Poppins",
            fontFamily: "Poppins",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: -1,
            source: "google",
          },
          {
            name: "Proxima Nova",
            fontFamily: "proxima-nova",
            type: "sans-serif",
            weights: [400, 600, 700, 800, 900],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Questa Sans",
            fontFamily: "questa-sans",
            type: "sans-serif",
            weights: [400, 500, 700, 900],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Questa Slab",
            fontFamily: "questa-slab",
            type: "serif",
            weights: [400, 500, 700, 900],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Questa",
            fontFamily: "questa",
            type: "serif",
            weights: [400, 500, 700, 900],
            offset: 1,
            source: "adobe",
          },
          {
            name: "Roboto Mono",
            fontFamily: "Roboto Mono",
            type: "monospace",
            weights: [400, 500, 600, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "Roboto",
            fontFamily: "Roboto",
            type: "sans-serif",
            weights: [400, 500, 700],
            offset: 0,
            source: "google",
          },
          {
            name: "Rubik",
            fontFamily: "Rubik",
            type: "sans-serif",
            weights: [400, 500, 600, 700, 800, 900],
            offset: 0,
            source: "google",
          },
          {
            name: "Soleil",
            fontFamily: "soleil",
            type: "sans-serif",
            weights: [400, 600, 700, 800, 900],
            offset: 0,
            source: "adobe",
          },
          {
            name: "Zilla Slab",
            fontFamily: "Zilla Slab",
            type: "serif",
            weights: [400, 500, 600, 700],
            offset: 1,
            source: "google",
          },
        ];
