import type { Schema } from "prosemirror-model";

import { createEditor } from "./editor";
import {
  Bold,
  BulletList,
  Callout,
  CharacterCount,
  Code,
  CodeBlock,
  Details,
  Dropcursor,
  Emoji,
  Focus,
  FontFamily,
  FontSize,
  Footnote,
  Gapcursor,
  HardBreak,
  Heading,
  Highlight,
  HorizontalRule,
  Image,
  Italic,
  LineHeight,
  Link,
  LinkCard,
  ListItem,
  Lists,
  Mention,
  OrderedList,
  Placeholder,
  Quote,
  Redo,
  Separator,
  SlashMenu,
  Strike,
  StripFormatting,
  Subscript,
  Superscript,
  Table,
  TableOfContents,
  TaskList,
  TrailingNode,
  TextAlign,
  TextColor,
  TextDirection,
  TextStyle,
  Typography,
  Underline,
  Undo,
  UniqueID,
  YouTube,
} from "./editor/extensions";

export const editor = createEditor([
  Undo,
  Redo,
  Separator,
  TextStyle,
  Heading,
  Lists,
  BulletList,
  OrderedList,
  ListItem,
  TaskList,
  Quote,
  CodeBlock,
  Details,
  Callout,
  Separator,
  Bold,
  Italic,
  Strike,
  Code,
  Underline,
  Separator,
  FontFamily,
  FontSize,
  TextColor,
  Highlight,
  Link,
  Separator,
  Superscript,
  Subscript,
  StripFormatting,
  Separator,
  TextAlign,
  TextDirection,
  LineHeight,
  Separator,
  HorizontalRule,
  HardBreak,
  Table,
  Image,
  YouTube,
  LinkCard,
  Footnote,
  Typography,
  Gapcursor,
  Dropcursor,
  Placeholder,
  TrailingNode,
  CharacterCount,
  Focus,
  UniqueID,
  TableOfContents,
  SlashMenu,
  Mention,
  Emoji,
] as const);

export type EditorCommand = Parameters<typeof editor.useRunCommand>[0];

export function buildInitialDoc(schema: Schema) {
  return schema.nodes["doc"]!.create(null, [
    schema.nodes["heading"]!.create({ level: 1 }, schema.text("Hello, Pitter Patter")),
    schema.nodes["paragraph"]!.create(null, [
      schema.text("Marks: "),
      schema.text("bold", [schema.marks["strong"]!.create()]),
      schema.text(", "),
      schema.text("highlighted", [schema.marks["highlight"]!.create()]),
      schema.text(", "),
      schema.text("link", [schema.marks["link"]!.create({ href: "https://example.com" })]),
      schema.text("."),
    ]),
    schema.nodes["bullet_list"]!.create(null, [
      schema.nodes["list_item"]!.create(
        null,
        schema.nodes["paragraph"]!.create(
          null,
          schema.text("Type 1. inside this bullet to switch to ordered."),
        ),
      ),
      schema.nodes["list_item"]!.create(
        null,
        schema.nodes["paragraph"]!.create(
          null,
          schema.text("Press Enter twice on an empty item to lift out."),
        ),
      ),
    ]),
    schema.nodes["paragraph"]!.create(null, [
      schema.text("Click the image button to insert one — try "),
      schema.text("https://picsum.photos/200", [schema.marks["code"]!.create()]),
      schema.text("."),
    ]),
  ]);
}
